### PR TITLE
Null handling for Categories, Entries, and Pages. (#89)

### PR DESCRIPTION
**Pull request by The-Fireplace**
I left TODOs for changes that should be made, but could potentially break other mods' guides.

### CODE REVIEW

**Comment by TehNut** [comment]
Honestly I would rather add Nullability annotations with Precondition checks.

```java
public void addCategory(@Nonnull CategoryAbstract category) {
    Preconditions.checkNotNull(category, "category cannot be null");

    // Do stuff
}
```

If given a null, this would give a warning in the dev environment and outright crash at runtime. It's the style I'm moving to in [all of my projects](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/api_impl/BloodMagicRecipeRegistrar.java#L36-L88) now.

**Comment by The-Fireplace** [comment]
There, is that better?

**Comment by TehNut** [comment]
I meant in general. I do not want null to be acceptable at all.

**Comment by The-Fireplace** [comment]
The only way to do that will be to make breaking changes. Do you want me to do that?

**Comment by TehNut** [comment]
V

**Pull request closed without merging**
